title: Mosiac`s github page
author: Mosaic 
email: mosesk.ogun@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Mosaic`s blog gives you updates on current innovation in science and technology globally

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
